<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Sidekick.UI.XF</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.848062" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xodium.Core\Xodium.Core.csproj" />
    <ProjectReference Include="..\..\Xodium.Mvvm\Xodium.Mvvm.csproj" />
    <ProjectReference Include="..\Sidekick.Core\Sidekick.Core.csproj" />
  </ItemGroup>

</Project>
