<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="19.5.1" />
    <PackageReference Include="ReactiveUI.XamForms" Version="19.5.1" />
    <PackageReference Include="Xamarin.Forms" Version="5.0.0.2612" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sidekick.Shopper.Main\Sidekick.Shopper.Main.csproj" />
    <ProjectReference Include="..\Sidekick.UI.XF\Sidekick.UI.XF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\ShoppingFolderView.xaml.cs">
      <DependentUpon>ShoppingFolderView.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
