<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI.XamForms" Version="10.3.6" />
    <PackageReference Include="Xamarin.Forms" Version="4.2.0.848062" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sidekick.Shopper.Main\Sidekick.Shopper.Main.csproj" />
    <ProjectReference Include="..\Sidekick.UI.XF\Sidekick.UI.XF.csproj" />
  </ItemGroup>

</Project>
