<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Torsten Seemann</Authors>
    <Description>Xodium Library, Xamarin plugins support</Description>
    <Product>Xodium</Product>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Xodium_64.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Plugin.Share" Version="7.1.1" />
    <PackageReference Include="Rg.Plugins.Popup" Version="2.1.0" />
    <PackageReference Include="Xam.Plugin.Geolocator" Version="4.5.0.6" />
    <PackageReference Include="Xam.Plugin.Media" Version="6.0.2" />
    <PackageReference Include="Xam.Plugins.Settings" Version="3.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Core\Xodium.Core.csproj" />
    <ProjectReference Include="..\Xodium.Platform.Common\Xodium.Platform.Common.csproj" />
    <ProjectReference Include="..\Xodium.Platform.Xamarin\Xodium.Platform.Xamarin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\images\Xodium_64.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
