<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <WasmHead>true</WasmHead>
    <DefineConstants>$(DefineConstants);__WASM__</DefineConstants>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\Sidekick.Uno.UWP\Assets\*.png" Link="Assets\%(FileName)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="WasmCSS\Fonts.css" />
    <EmbeddedResource Include="WasmScripts\AppManifest.js" />
  </ItemGroup>
  <ItemGroup>
    <LinkerDescriptor Include="LinkerConfig.xml" />
  </ItemGroup>
  <ItemGroup>
    <!-- 
    This item group is required by the project templace because of the
    new SDK-Style project, otherwise some files are not aded automatically.
    
    You can safely remove this ItemGroup completely.
    -->
    <Compile Remove="Program.cs" />
    <Compile Include="Program.cs" />
    <Content Include="LinkerConfig.xml" />
    <Content Include="wwwroot/web.config" />
  </ItemGroup>
  <ItemGroup>
    <!-- Note that for WebAssembly version 1.1.1 of the console logger required -->
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.2" />
    <PackageReference Include="Uno.UI" Version="3.10.11" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="3.0.0" />
    <DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.244" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Xodium.Core\Xodium.Core.csproj" />
    <ProjectReference Include="..\..\Xodium.Redux\Xodium.Redux.csproj" />
    <ProjectReference Include="..\Sidekick.Core\Sidekick.Core.csproj" />
    <ProjectReference Include="..\Sidekick.Main\Sidekick.Main.csproj" />
    <ProjectReference Include="..\Sidekick.Shopper.Core\Sidekick.Shopper.Core.csproj" />
    <ProjectReference Include="..\Sidekick.Shopper.Main\Sidekick.Shopper.Main.csproj" />
    <ProjectReference Include="..\Sidekick.UI.Uno\Sidekick.UI.Uno.csproj" />
  </ItemGroup>
  <Import Project="..\Sidekick.Uno.Shared\Sidekick.Uno.Shared.projitems" Label="Shared" Condition="Exists('..\Sidekick.Uno.Shared\Sidekick.Uno.Shared.projitems')" />
  <Import Project="..\Sidekick.Shopper.UI.Uno\Sidekick.Shopper.UI.Uno.projitems" Label="Shared" Condition="Exists('..\Sidekick.Shopper.UI.Uno\Sidekick.Shopper.UI.Uno.projitems')" />
</Project>