<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Sidekick</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Xodium.Core\Xodium.Core.csproj" />
    <ProjectReference Include="..\..\Xodium.Mvvm\Xodium.Mvvm.csproj" />
    <ProjectReference Include="..\..\Xodium.Redux\Xodium.Redux.csproj" />
    <ProjectReference Include="..\Sidekick.Shopper.Core\Sidekick.Shopper.Core.csproj" />
  </ItemGroup>

</Project>
