<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Authors>Torsten Seemann</Authors>
    <Company>Torsten Seemann</Company>
    <Product>Xodium</Product>
    <Description>Xodium Library, Redux.NET support for unidirectional dataflow state management</Description>
    <LangVersion>latest</LangVersion>
    <PackageIconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</IconUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Redux.NET" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Core\Xodium.Core.csproj" />
  </ItemGroup>

</Project>
