<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>Torsten Seemann</Authors>
    <Company>Torsten Seemann</Company>
    <Product>Xodium</Product>
    <Description>Xodium MVVM Framework, base types</Description>
    <LangVersion>latest</LangVersion>
    <IconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</IconUrl>
    <PackageIconUrl></PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Xodium_64.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\images\Xodium_64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Core\Xodium.Core.csproj" />
  </ItemGroup>

</Project>
