<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Xodium MVVM Framework, Reactive UI support</Description>
    <Authors>Torsten Seemann</Authors>
    <Company>Torsten Seemann</Company>
    <Product>Xodium</Product>
    <PackageIconUrl>https://raw.githubusercontent.com/tseemann-dk/Xodium/master/images/Xodium_128.png?token=ALELTYON4A56XE4RCJ5KD725HDOAM</PackageIconUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="9.19.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Mvvm\Xodium.Mvvm.csproj" />
  </ItemGroup>

</Project>
