<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Xodium MVVM Framework, Reactive UI support</Description>
    <Authors>Torsten Seemann</Authors>
    <Company>Torsten Seemann</Company>
    <Product>Xodium</Product>
    <IconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</IconUrl>
    <PackageIconUrl></PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Xodium_64.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\images\Xodium_64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="19.6.12" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Mvvm\Xodium.Mvvm.csproj" />
  </ItemGroup>

</Project>
