<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Xodium</RootNamespace>
    <Authors>Torsten Seemann</Authors>
    <Product>Xodium</Product>
    <Description>Xodium Library, Core types</Description>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
    <Company>Torsten Seemann</Company>
    <IconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</IconUrl>
    <PackageIconUrl></PackageIconUrl>
    <Copyright>Copyright (c) Torsten Seemann</Copyright>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl>https://github.com/tseemann-dk/Xodium</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>Xodium_64.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.2.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\images\Xodium_64.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
