<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageIcon>Xodium_64.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\images\Xodium_64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Data\Xodium.Data.csproj" />
  </ItemGroup>

</Project>
