<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <Authors>Torsten Seemann</Authors>
    <Company>Torsten Seemann</Company>
    <Product>Xodium</Product>
    <Description>Xodium MVVM Framework, Xamarin Forms support</Description>
    <LangVersion>latest</LangVersion>
    <IconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</IconUrl>
    <PackageIconUrl>https://tseemann-dk.github.io/images/Xodium_64.png</PackageIconUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Rg.Plugins.Popup" Version="1.1.5.188" />
    <PackageReference Include="Xamarin.Forms" Version="4.1.0.618606" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xodium.Mvvm\Xodium.Mvvm.csproj" />
    <ProjectReference Include="..\Xodium.Platform.Xamarin\Xodium.Platform.Xamarin.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

</Project>
